application: getpitchd
version: 0
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /.*/static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static

- url: .*
  script: urls.app